### ISSUE TITLE
Request PHP report spreadsheet extract - Contracts-Provider-Incentive-FTE-Effective-Default expiration-Status

### ISSUE THREAD

**Issue by WjohnsonKPN** [zkeene/qualitydb#55]

**Comment by zkeene** [comment]
`SELECT provider_name, total_incentive_amount, fte, effective_quality_date, default_expire_date, active FROM providers, contracts WHERE providers.id = contracts.provider_id ORDER BY provider_name asc`

This query can be run to get the data, is this a report that will need to be run on a regular basis? If so, I'll write it in PHP.
