### ISSUE TITLE
Request PHP report spreadsheet extract - Provider-by Service Line-SER-NPI-Badge-Status

### ISSUE THREAD

**Issue by WjohnsonKPN** [zkeene/qualitydb#56]

**Comment by zkeene** [comment]
`SELECT service_line, provider_name, SER, NPI, badge_num, provider_status FROM providers, service_lines WHERE service_lines.id = providers.service_line_id ORDER BY service_line, provider_name asc`

This query can be run to get the data, is this a report that will need to be run on a regular basis? If so, I'll write it in PHP.
