### ISSUE TITLE
Physician Active/Inactive date

### ISSUE THREAD

**Issue by cmaxson08** [zkeene/qualitydb#59]
Is there any way to add an Active/Effective & Inactive field under the providers section? This would allow us to add upcoming effective or inactive dates for providers reducing unnecessary scorecards being produced for providers that are in the system but not effective during the current quarter.

**Comment by cmaxson08** [comment]
Pend until date. :)

**Comment by zkeene** [comment]
need to add new date field to provider table and write code in scorecard to ignore provider if date has not yet passed

**Comment by zkeene** [comment]
Should I just change the contract effective date to be the trigger? Since a date really isnt associated with a provider but is associated with their contract

**Comment by cmaxson08** [comment]
I believe the effective date for the contract is already the trigger for the contract, which is helpful. But we also have a lot of providers starting right after the quarter that either don’t have a contract with money attached or if they do we can’t add them until this quarter is paid because it will generate a scorecard and it shouldn’t. Is this something that’s even doable?

Courtney Maxson
KPN Quality-Austin Landing
Courtney.maxson@ketteringhealth.org
Phone: 937-558-3483
Fax: 937-522-7252

**Comment by cmaxson08** [comment]
Yes the contract effective date. Thank you.

**Comment by christinakettering12345** [comment]
past
