### ISSUE TITLE
Give Scorecard and GitHub access to Blake Moreland (new employee)

### ISSUE THREAD

**Issue by WjohnsonKPN** [zkeene/qualitydb#64]
Please give Scorecard and GitHub access to Blake Moreland (new employee).  Thanks

**Comment by zkeene** [comment]
Webserver and MySQL accounts created for Blake. Instructions for connecting sent.

**Comment by WjohnsonKPN** [comment]
Thanks!

**Comment by WjohnsonKPN** [comment]
thx
